//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace WcfCommService {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    [System.Xml.Serialization.XmlRootAttribute("comment", Namespace="http://doodle.com/xsd1", IsNullable=false)]
    public partial class CommentType {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string whoField;
        
        private string userIdField;
        
        private System.DateTime whenField;
        
        private bool whenFieldSpecified;
        
        private string whatField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string who {
            get {
                return this.whoField;
            }
            set {
                this.whoField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime when {
            get {
                return this.whenField;
            }
            set {
                this.whenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool whenSpecified {
            get {
                return this.whenFieldSpecified;
            }
            set {
                this.whenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string what {
            get {
                return this.whatField;
            }
            set {
                this.whatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public partial class CommentsType {
        
        private CommentType[] commentField;
        
        private string nrOfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comment")]
        public CommentType[] comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string nrOf {
            get {
                return this.nrOfField;
            }
            set {
                this.nrOfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public partial class ParticipantsType {
        
        private ParticipantType[] participantField;
        
        private string nrOfField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("participant")]
        public ParticipantType[] participant {
            get {
                return this.participantField;
            }
            set {
                this.participantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string nrOf {
            get {
                return this.nrOfField;
            }
            set {
                this.nrOfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    [System.Xml.Serialization.XmlRootAttribute("participant", Namespace="http://doodle.com/xsd1", IsNullable=false)]
    public partial class ParticipantType {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string participantKeyField;
        
        private string nameField;
        
        private string targetCalendarIdField;
        
        private string userIdField;
        
        private string participantFirstNameField;
        
        private string participantLastNameField;
        
        private string participantPostalAddressField;
        
        private string participantEmailAddressField;
        
        private string participantPhoneNumberField;
        
        private string[] preferencesField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string participantKey {
            get {
                return this.participantKeyField;
            }
            set {
                this.participantKeyField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string targetCalendarId {
            get {
                return this.targetCalendarIdField;
            }
            set {
                this.targetCalendarIdField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string participantFirstName {
            get {
                return this.participantFirstNameField;
            }
            set {
                this.participantFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string participantLastName {
            get {
                return this.participantLastNameField;
            }
            set {
                this.participantLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string participantPostalAddress {
            get {
                return this.participantPostalAddressField;
            }
            set {
                this.participantPostalAddressField = value;
            }
        }
        
        /// <remarks/>
        public string participantEmailAddress {
            get {
                return this.participantEmailAddressField;
            }
            set {
                this.participantEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string participantPhoneNumber {
            get {
                return this.participantPhoneNumberField;
            }
            set {
                this.participantPhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("option", DataType="integer", IsNullable=false)]
        public string[] preferences {
            get {
                return this.preferencesField;
            }
            set {
                this.preferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public partial class InitiatorType {
        
        private string nameField;
        
        private string userIdField;
        
        private string eMailAddressField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string eMailAddress {
            get {
                return this.eMailAddressField;
            }
            set {
                this.eMailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public partial class ByInvitationOnlyType {
        
        private string nrOfInviteesField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string nrOfInvitees {
            get {
                return this.nrOfInviteesField;
            }
            set {
                this.nrOfInviteesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public partial class ExtensionsType {
        
        private bool timeZoneField;
        
        private bool timeZoneFieldSpecified;
        
        private string columnConstraintField;
        
        private string rowConstraintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeZoneSpecified {
            get {
                return this.timeZoneFieldSpecified;
            }
            set {
                this.timeZoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string columnConstraint {
            get {
                return this.columnConstraintField;
            }
            set {
                this.columnConstraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string rowConstraint {
            get {
                return this.rowConstraintField;
            }
            set {
                this.rowConstraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    [System.Xml.Serialization.XmlRootAttribute("features", Namespace="http://doodle.com/xsd1", IsNullable=false)]
    public partial class FeaturesType {
        
        private FeatureType[] featureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("feature")]
        public FeatureType[] feature {
            get {
                return this.featureField;
            }
            set {
                this.featureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public enum FeatureType {
        
        /// <remarks/>
        useCustomURL,
        
        /// <remarks/>
        useCustomLogo,
        
        /// <remarks/>
        hideAds,
        
        /// <remarks/>
        hideDoodleFor,
        
        /// <remarks/>
        useCustomDecoration,
        
        /// <remarks/>
        useCustomCSS,
        
        /// <remarks/>
        requireAuth,
        
        /// <remarks/>
        useSSL,
        
        /// <remarks/>
        customTheme,
        
        /// <remarks/>
        avatar,
        
        /// <remarks/>
        extraInformation,
        
        /// <remarks/>
        quickReply,
        
        /// <remarks/>
        pickSubCalendar,
        
        /// <remarks/>
        smsLink,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    [System.Xml.Serialization.XmlRootAttribute("poll", Namespace="http://doodle.com/xsd1", IsNullable=false)]
    public partial class PollType {
        
        private System.DateTime latestChangeField;
        
        private bool latestChangeFieldSpecified;
        
        private PollTypeType typeField;
        
        private bool typeFieldSpecified;
        
        private ExtensionsType extensionsField;
        
        private bool hiddenField;
        
        private bool hiddenFieldSpecified;
        
        private bool writeOnceField;
        
        private bool writeOnceFieldSpecified;
        
        private bool requireAddressField;
        
        private bool requireAddressFieldSpecified;
        
        private bool requireEMailField;
        
        private bool requireEMailFieldSpecified;
        
        private bool requirePhoneField;
        
        private bool requirePhoneFieldSpecified;
        
        private ByInvitationOnlyType byInvitationOnlyField;
        
        private string levelsField;
        
        private StatesType stateField;
        
        private bool stateFieldSpecified;
        
        private string titleField;
        
        private string locationField;
        
        private string descriptionField;
        
        private InitiatorType initiatorField;
        
        private OptionsTypeOption[] optionsField;
        
        private ParticipantsType participantsField;
        
        private CommentsType commentsField;
        
        private string mandatorField;
        
        private FeatureType[] featuresField;
        
        /// <remarks/>
        public System.DateTime latestChange {
            get {
                return this.latestChangeField;
            }
            set {
                this.latestChangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latestChangeSpecified {
            get {
                return this.latestChangeFieldSpecified;
            }
            set {
                this.latestChangeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PollTypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ExtensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        public bool hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hiddenSpecified {
            get {
                return this.hiddenFieldSpecified;
            }
            set {
                this.hiddenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool writeOnce {
            get {
                return this.writeOnceField;
            }
            set {
                this.writeOnceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool writeOnceSpecified {
            get {
                return this.writeOnceFieldSpecified;
            }
            set {
                this.writeOnceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool requireAddress {
            get {
                return this.requireAddressField;
            }
            set {
                this.requireAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requireAddressSpecified {
            get {
                return this.requireAddressFieldSpecified;
            }
            set {
                this.requireAddressFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool requireEMail {
            get {
                return this.requireEMailField;
            }
            set {
                this.requireEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requireEMailSpecified {
            get {
                return this.requireEMailFieldSpecified;
            }
            set {
                this.requireEMailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool requirePhone {
            get {
                return this.requirePhoneField;
            }
            set {
                this.requirePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requirePhoneSpecified {
            get {
                return this.requirePhoneFieldSpecified;
            }
            set {
                this.requirePhoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ByInvitationOnlyType byInvitationOnly {
            get {
                return this.byInvitationOnlyField;
            }
            set {
                this.byInvitationOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string levels {
            get {
                return this.levelsField;
            }
            set {
                this.levelsField = value;
            }
        }
        
        /// <remarks/>
        public StatesType state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public InitiatorType initiator {
            get {
                return this.initiatorField;
            }
            set {
                this.initiatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("option", IsNullable=false)]
        public OptionsTypeOption[] options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        public ParticipantsType participants {
            get {
                return this.participantsField;
            }
            set {
                this.participantsField = value;
            }
        }
        
        /// <remarks/>
        public CommentsType comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string mandator {
            get {
                return this.mandatorField;
            }
            set {
                this.mandatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("feature", IsNullable=false)]
        public FeatureType[] features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public enum PollTypeType {
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        TEXT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://doodle.com/xsd1")]
    public enum StatesType {
        
        /// <remarks/>
        OPEN,
        
        /// <remarks/>
        CLOSED,
        
        /// <remarks/>
        DELETED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://doodle.com/xsd1")]
    public partial class OptionsTypeOption {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        private System.DateTime startDateTimeField;
        
        private bool startDateTimeFieldSpecified;
        
        private System.DateTime endDateTimeField;
        
        private bool endDateTimeFieldSpecified;
        
        private bool finalField;
        
        private bool finalFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateTimeSpecified {
            get {
                return this.startDateTimeFieldSpecified;
            }
            set {
                this.startDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime endDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateTimeSpecified {
            get {
                return this.endDateTimeFieldSpecified;
            }
            set {
                this.endDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool final {
            get {
                return this.finalField;
            }
            set {
                this.finalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finalSpecified {
            get {
                return this.finalFieldSpecified;
            }
            set {
                this.finalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
